### ISSUE TITLE
Add Chain Version into NEP description

### ISSUE THREAD

**Issue by lock9** [neo-project/proposals#100]
Hello,
@lllwvlvwlll  [suggested](https://github.com/neo-project/neo/issues/973#issuecomment-516964759) that we add the Chain Version in our NEPs.
I think this is a good practice, since if when we update NEO, we may affect NEPs.

**Comment by igormcoelho** [comment]
We could update past NEPs to inform which networks they refer to.
A field: 'protocol' : 2+, 2, 3, 3+

**Comment by erikzhang** [comment]
We should abolish the NEO2 NEPs when NEO3 MainNet is launched.

**Comment by igormcoelho** [comment]
I think all existing ones can be migrated Erik... not too much incompatible stuff I guess (haven't seen yet).

**Comment by lock9** [comment]
Hi @erikzhang, but we are keeping both neo2 and neo3 running simultaneously for some time, aren't we? At least during this period of time, we need to describe if the NEPs are compatible. 
Today we are updating NEP-3 for neo 3 and these changes are not compatible with neo 2, however, neo 2 is the current version in production mode. This may cause issues for new developers.

I believe this is an good opportunity to filter what neps are included in neo3 and which are 'discarded'. @erikzhang  do you think there will be negative impacts? Because if there are only positive impacts (even if they are very small), maybe we can put this forward? 😅 
It is a demand from our communities, they need to know in order to replicate it into their tools
