### ISSUE TITLE
Create ANOTHER NEP standard for fundamental changes

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/proposals#115]
There were changes directly on the NEP-3. This brings a lot of confusion to the community, IMHO.
If NEP-3 (or NEO-6) is modified in some fundamental way, then, let's do another NEP standard as any other blockchain project. In the example from above, removing an entrypoint is a fundamental change. For sure, no doubts.

If only pieces of text and no functionality is modified, then, it's fine, it's just an amendment and the NEP number should remain untouched.

_original posted by @gsmachado_

What do you think? @neo-project/core

**Comment by Tommo-L** [comment]
I think it's pretty good, it's better to create a new NEP for fundamental changes, and discard the old one.

**Comment by erikzhang** [comment]
We can create another branch for neo 2.x. But we shouldn't change the NEP numbers.

**Comment by shargon** [comment]
At least should be a branch

**Comment by Tommo-L** [comment]
> We can create another branch for neo 2.x. But we shouldn't change the NEP numbers.

This just solves NEP3's puzzle. 

I think we'd better decide the process flow for the fundamental changes in the future. After we decided, we can update readme or create a NEP standard.

**Comment by gsmachado** [comment]
I think we should create another NEP number. For example, NEP-3 refers to something agreed in the past, with the entrypoint and all the other details. That constitutes a functionality in the system.

However, if we keep amending NEP standards, how SDKs libraries and other systems would refer to the implementation they have and what do they support? Do they support NEP-3 or not? Depends. This creates huge confusion and problems for the community!

All blockchain projects that I know, also [IETF RFCs](https://en.wikipedia.org/wiki/Request_for_Comments) (which inspired blockchain projects), change standard numbers once something fundamentally changes. I think we should do exactly the same.

**Comment by gsmachado** [comment]
My point is:
If we need to remove or add functionalities in NEPs, we should create another NEP.
If we need to fix something small or amend, we should just fix and not create another NEP.

**Comment by erikzhang** [comment]
I agree. But NEO3 is a new chain. You can consider that all numbers are reset.

**Comment by gsmachado** [comment]
@erikzhang I'm bringing this topic exactly because "Neo3 is a new chain". 😄 👌 

Because Neo3 is a new chain, something new, we might need/have different/new standards than Neo2.

Neo3 is a new chain and needs new standards, new NEPs. The old NEPs related to Neo2 should remain how they are, untouched. And that's fine! If someone wants, somehow, to take `master-2.x` of [neo-project/neo-node](https://github.com/neo-project/neo-node/tree/master-2.x) and run a chain, they will know that SDKs supporting NEP-3, NEP-2, and NEP-6, will work with that specific Neo node (Neo2, in this example).

Now, imagine that someone takes `master` (Neo3) of [neo-project/neo-node](https://github.com/neo-project/neo-node/tree/master) and run a chain. This person will need a release of an SDK which is compatible with NEP-3 (as stated in the docs in the [neo-project/neo-node](https://github.com/neo-project/neo-node/tree/master)). Then, this person will find a version of an SDK that says, in their documentation: "this SDK supports NEP-3". But which NEP-3? The new NEP-3? Or the "old" (Neo2) NEP-3? It's not clear.

Moreover, creating new NEP numbers would avoid confusion on documentation or features that will **not be updated** out there in the wild. With different NEP numbers, it would be clear what software/SDKs/libs would support or not.

I'm not reinventing the wheel here. Again: many standards work like this, including BIP, IETF RFC, and others. Always create a new one, making a reference to the past.

But, if you see any clear advantage of why the Neo community should keep standards in a different way I would be super curious to hear and get convinced. 👍 😃

**Comment by devhawk** [comment]
I think it's important that the master branch of this repo contains all of the NEPs for Neo2 and Neo3, at least while Neo2 is in production. The specifics of how this done don't seem that important to me. Any of these approaches should work:

* Keep NEP numbering, but explicitly describe the Neo2 and Neo3 behavior. 
* Create new NEPs for Neo3 versions of updated Neo2 NEPs
* Create a new prefix or numbering scheme. For example, Python PEPs for Python 3 [started their numbering at 3000](https://www.python.org/dev/peps/pep-3000/#pep-numbering)

**Comment by lllwvlvwlll** [comment]
We need to make sure not to retroactively break project conformity.  This topic has been discussed at extreme lengths and nearly destroyed this community when we proposed enhancements to NEP5.  We need to maintain existing standards and introduce revisions through a new standards number.  There is 0 implementation cost to doing this and we have everything to gain from this approach.

For clarity when discussing these, we should use a different acronym for neo2; the numbers can be identical for now, but its going to get VERY complicated in regular discussions when talking about NEP5 (neo2 or neo3).

I am a fan of @devhawk 's second and third proposals together.

**Comment by gsmachado** [comment]
Yes, I also vote for @devhawk 's second and their proposals together. Good idea. 😃

**Comment by shargon** [comment]
`NEP-3001` sounds good

**Comment by Tommo-L** [comment]
I think most people have reached a consensus. If possible, we should make the following changes:

1. Add an optional `neo-version` attribute in NEP1 header preamble to describe the specific version to which the NEP is applicable. For example, NEP3 is only for neo-2.x at present.
2. Specify the condition of "repalce" NEP in NEP1. We can add the sentence like "remove or add functionalities in NEPs, we should create another NEP".
3. Restore NEP3 and add `neo-version:2.x` attribute.
4. Add NEP3000 standard to describe the NEP numbering of NEO3.
4. Add NEP3001 standard of NEO3 ABI.
5. Add NEP3002 standard of NEO3 Contract Manifest.

**Comment by erikzhang** [comment]
I have created the branch [master-2.x](https://github.com/neo-project/proposals/tree/master-2.x), and reverted all the changes from NEO3.

**Comment by devhawk** [comment]
> I have created the branch [master-2.x](https://github.com/neo-project/proposals/tree/master-2.x), and reverted all the changes from NEO3.

Why? These should all be in master branch, NEO3 NEPs will all be NEP-30xx right?

**Comment by erikzhang** [comment]
I think you are right. However, NEP numbers should not start at 3000. Because there will no longer be NEPs applied to NEO2, there is no need to reserve numbers for NEO2.

**Comment by erikzhang** [comment]
This is the reverting PR: #118

**Comment by ixje** [comment]
> I think you are right. However, NEP numbers should not start at 3000. Because there will no longer be NEPs applied to NEO2, there is no need to reserve numbers for NEO2.

It is **_not_** about reserving NEP numbers for `2.x`. The point of prefixing with `3xxx` is that **_everybody_**  can immediately deduce that the NEP only applies to the `3.x` chain. If we just take the next available NEP number (e.g. 14) to start describing `3.x` chain related items then people need to know where this boundary lies. 

We could even have an additional benefit if we re-use "famous" NEP numbers for the same content. e.g. NEP5 -> NEP3005. Both describe the Token standard but for different chain version. Long term NEO supporters can keep referring to arguably the same number. The down side of this would be gaps in the numbering if certain old features are not ported to `3.x`.

**Comment by erikzhang** [comment]
> The point of prefixing with 3xxx is that everybody can immediately deduce that the NEP only applies to the 3.x chain.

@ixje I think everything applies to 3.x. The old NEP-3 will be abolished and be marked as `Replaced`. The good ones such as NEP-5 should be retained. I don't want to create a new NEP-3005 that is exactly the same as NEP-5.

**Comment by shargon** [comment]
I think that we are mixing different blockchains with same NEPs, in two years, when neo2 will be obsolete and only neo3 will exists, why the users need to know the old NEP5? this it's confusing for the users. But if we move the obsolete NEPs to a different folder and we say in the NEP that it's for NEO2, it's ok for me.

**Comment by ixje** [comment]
gsmachado @ https://github.com/neo-project/proposals/issues/115#issuecomment-602451838
and
devhawk @ https://github.com/neo-project/proposals/issues/115#issuecomment-602631979

have given all the arguments for how, how long and why you want to preserve the `2.x` NEPS. No point in reiterating those posts.

**Comment by erikzhang** [comment]
> But if we move the obsolete NEPs to a different folder ...

Good idea. It should be done after #118.

**Comment by erikzhang** [comment]
@ixje I agreed to use new numbers, but not start from 3000.
