### ISSUE TITLE
Remove `from` argument from NEP5

### ISSUE THREAD

**Issue by shargon** [neo-project/proposals#117]
Should we remove the `from` argument from NEP5 and use the `Sender` of the transaction in order to avoid user mistakes?

https://github.com/neo-project/proposals/blob/master/nep-5.mediawiki#transfer

**Comment by erikzhang** [comment]
Consider that you have a wallet with two addresses. One has NEO and another has GAS. If you want to transfer NEO, you need the `from` argument.

**Comment by shargon** [comment]
Good example! I will close it
