### ISSUE TITLE
Broken link in NEP-6

### ISSUE THREAD

**Issue by mialbu** [neo-project/proposals#176]
The link to one of the implementation examples in the NEP-6 standard is broken. Likely due to some dir name changes in the `/neo` repo recently.

Current link:
https://github.com/neo-project/neo/blob/master/src/neo/Wallets/NEP6/NEP6Wallet.cs

Should be the following:
https://github.com/neo-project/neo/blob/master/src/Neo/Wallets/NEP6/NEP6Wallet.cs

**Comment by roman-khimov** [comment]
It better have some fixed commit then, `master` can change in any way.

**Comment by mialbu** [comment]
> It better have some fixed commit then, `master` can change in any way.

I agree. I proposed that one because the links to implementation examples I've seen in other NEPs also don't use permalinks. So, if you're going to use a permalink here, maybe the the implementation links in other NEPs should be replaced with permalinks as well.
