### ISSUE TITLE
Extend nep-19

### ISSUE THREAD

**Issue by shargon** [neo-project/proposals#184]
I would like to extend the nep-19 with the following information:

- Add `abi` method information to the method entry if the method is exported. This JSON will match the method object in ABI format.
- Add `sequence-points-v2` to the method information, containing the following data:

```json
"sequence-points-v2": {
    "20": { // ofsset
      "optimized": "none",  // optimization type
      "source": { // source information
        "document": 0, // document index
        "location": "12:20-12:21" // range
      },
      "compiler": { // compiler information
        "file": "Expression.cs", // file
        "line": 36, // line
        "method": "ConvertExpression" // method
      }
    }
}
```

The entries of source and compiler is `JObject`, but `JArray` can be expected when `optimization` is not none.

**All is backward compatible.**

Note: also the NGD link is broken

> Details regarding older versions of the debug info format is available in the [original Design Note](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md).

**Comment by ixje** [comment]
* This should be a new NEP, not updating the old one. You could say that your compiler supports NEP-19 + NEP-XX.
* What is the rationale for other compilers to have this? Or in other words, why can't this just be a separate file format for the C# compiler? as it seems to be to help you debug your compiler

**Comment by shargon** [comment]
> * This should be a new NEP, not updating the old one. You could say that your compiler supports NEP-19 + NEP-XX.
> * What is the rationale for other compilers to have this? Or in other words, why can't this just be a separate file format for the C# compiler? as it seems to be to help you debug your compiler

New nep is good for me, no nep is good for me also (is compatible) but new file is not good for me, make things complex without any necessity

**Comment by shargon** [comment]
Any extra json in the format has no influence in id the file is nep-19 compliant also.

Yes, it will help with the compiler, but also it allowsto use it with optimized nef files, now is not possible because we can have multiple sources associated to that offset, and also, it doesn't mix cvs file style with json one, something totally weird.

**Comment by ixje** [comment]
> Any extra json in the format has no influence in if the file is nep-19 compliant also.

It does if the consumer uses a strict JSON schema check. To be fair that's trivial to update.

> Yes, it will help with the compiler, but also it allowsto use it with optimized nef files, now is not possible because **we can have multiple sources associated to that offset**, and also, it doesn't mix cvs file style with json one, something totally weird.

How is that possible? All sequence points should have a unique combination of `source doc` + `src line(s)`  + `source column range`. 

> Also, allow to link the abi with the debug info, currently you can't identify if the method is exported or not as an abi method, very useful for reverse engineering or testing environments

Sure not directly from the debug information file, but that's also not the purpose of the file according to the [NEP-19 motivation](https://github.com/neo-project/proposals/blob/master/nep-19.mediawiki#motivation).

**Comment by roman-khimov** [comment]
> Any extra json in the format has no influence in if the file is nep-19 compliant also.

NEP-19 is not saying anything about it explicitly, but it defines a complete file format, so any additional data there would be at least unexpected and some tools can break if they see it. That's very different from NEP-17 which is explicitly a set of methods and associated behavior. Take NEP-25, it's a pure extension of NEP-14, but it can't work unless implemented properly everywhere, this manifest won't be accepted.

> allowsto use it with optimized nef files, now is not possible because we can have multiple sources associated to that offset

It's a different problem (that I'm very much interested in, https://github.com/nspcc-dev/neo-go/issues/2428) and internal compiler-specific data doesn't seem like a solution.

> it doesn't mix cvs file style with json one, something totally weird.

Well, that's what it is. But it's more compact currently.

> currently you can't identify if the method is exported or not as an abi method

That's easily available from manifest, I doubt you debug anything without manifest. Here NEP-19 just avoids duplication of ABI.

**Comment by Jim8y** [comment]
There is no need to extend nep-19, we just have a new NEP that works along with NEP19, if you prefer NEP 19, keep it that way, bue also wont prevent us from moving forward.

**Comment by shargon** [comment]
Ok, no nep changes, we will made an option to export this format strictly
