### ISSUE TITLE
NEP-3 ABI extension proposal

### ISSUE THREAD

**Issue by luodanwg** [neo-project/proposals#28]
Does the ABI can provide a mark, which can identifies the function whether perform onchain or offchain.

So the dapp developer needn't to care about the the smart contract detail or use which protocal to interact with the blockchain. SDK will use ABI to decided whether query on the node or make a transaction on the blockchain.

**Comment by roman-khimov** [comment]
To me NEP-14 `safe` attribute is as close to this as it could probably be, so I'd say it's done.
