### ISSUE TITLE
NEP 5: Token Standard

### ISSUE THREAD

**Issue by tanZiWen** [neo-project/proposals#3]
## Proposal
Name: NEP-5
Title:Token Standard
Author: luodanwg <luodan.wg@gmail.com>, tanyuan <tanyuan666@gmail.com>
Status: Draft
Created: 10 August 2017
Resolution: <a href="https://github.com/neo-project/proposals/pull/1"> Proposals </a>
Template:  <a href="https://github.com/tanZiWen/neo/wiki/NEO_NEP_5">NEO_NEP_5</a>
## Abstract 
The following describes standard functions a token contract can implement.
## Specification 
Token
Contracts that work with tokens
 ## Methods 
NOTE: The contract developers must implement all function if they want to work with the specified tokens. <br/>
**TotalSupply**
```csharp
 private static BigInteger TotalSupply()
```
 Get the total token supply

**Name**
```csharp
private static string Name()
```
Get the name of token

**Symbol**
```csharp
private static string Symbol()
```
Get the symbol of token, symbol used to represent a unit of token

**Decimals** 
```csharp
private static BigInteger Decimals()
```
Get decimals of token

**BalanceOf** 
```csharp
private static BigInteger BalanceOf(object[] args) 
```
Get the account balance of another account with address which is first element of args and type is <strong>byte[]</strong>

**Transfer** 
```csharp
private static bool Transfer(object[] args) 
```
function that is always called when someone wants to transfer tokens. The first element is sender address and type is <strong>byte[]</strong>, the second element is receiver address and type is <strong>byte[]</strong>, the third element is the number of token and type is <strong> BigInteger </strong>. 

## Event 
**Transferred**
```csharp
private static void Transferred(object[] args)
```
Triggered when tokens are transferred. args is the same with transfer.

**Comment by erikzhang** [comment]
Hi, can you work with @lllwvlvwlll in #4 who has done much work already?
