### ISSUE TITLE
New NEP: Composite Smart Contracts

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/proposals#40]
Joe and I are looking for feedback and will post this draft shortly to #dev-general. 

https://github.com/mwherman2000/proposals/blob/master/NEP-8.mediawiki [updated]

[It was short - 1 operation/method - so it was easy to write it up to get actual feedback.]

This NEP is very timely and relevant. Looking forward to everyone's feedback.

This based on the work Joe Stewart has done with Non-Fungbile Token extensions to NEP-5 and the work I've done to support NEP-5 extensions for Requisitions.

**Comment by Ejhfast** [comment]
This seems like a good idea to me. One reasonable assumption this proposal makes is that the standard will change or evolve in the future. (If the standard never changes, there would be no need for this method.) Maybe the rationale could include additional motivation for why it is likely the standard will fork or change in the future, justifying the existence of this method?

**Comment by mwherman2000** [comment]
Ethan, when you are referring to "the standard", can you clarify what you mean/are referring to? ...e,.g the proposed NEP, the subject NEPs, etc?

**Comment by Ejhfast** [comment]
I am referring to the NEP-5 standard, the standard that this proposal is aiming to improve.

**Comment by mwherman2000** [comment]
The proposed NEP applies to all NEPs not just NEP-5.

**Comment by saltyskip** [comment]
👍 For this, Can the return value be a JSON string instead? This also would allow for additional metadata to be put here in future about the contract.

e.g
```
{
	"standards": ["NEP-5", "NEP-1234"]
}
```

**Comment by erikzhang** [comment]
>For this, Can the return value be a JSON string instead? This also would allow for additional metadata to be put here in future about the contract.

Good idea!

**Comment by mwherman2000** [comment]
The proposed amendment is to return the following string
```
"{ \"standards\": [\"NEP-5\", \"NEP-1234\"] }"
```
instead of
```
"NEP-5", "NEP-1234"
```
Why choose a more complex string format? What are the use cases you can imagine and the additional value?  I think it's important to keep the `supportedStandards` protocol simple, practical and easy to implement.

Cons
1. We don't have JSON support in the VM or a supporting library to create *or parse* JSON strings. How would this work, for example, in the case of dynamically invoking one smart contract method from another?  
2. It goes against the pattern already established for `symbol`, `totalSupply`, `name`, etc.
3. JSON is already available as a serialization format between off-chain clients and `neo-cli`.

JSON is not simple, practical or easy to implement when you consider the need to create and parse JSON from inside the code for a NEO smart contract.

I believe it is best to stay with native data types supported by the NEO VM per the diagram below.

![enterprise dapp reference model-protocols](https://user-images.githubusercontent.com/6101736/39361944-9e07cf8c-49f2-11e8-9759-1bbac3fc5c52.png)

**Comment by saltyskip** [comment]
The majority of developers who consume any sort of data from a web request expect JSON. Even though it it may be more difficult for the contract maker to create a complex string, this is a one time operation.

Consuming the string will occur much more times than the creation of the string. Parsing is on the CLIENT side. People will just call invoke function, and hope for a simple response,

The complexity tradeoff concerns are negligible. If you make the response easy to consume it will incur more use in my opinion

**Comment by mwherman2000** [comment]
With no support for smart contract developers to create and parse JSON inside a smart contract, JSON is a non-starter.

**Comment by mwherman2000** [comment]
If the proposal was amended to return an array of strings, I think this meets both sets of requirements:

1. easily processable JSON is returned to the off-chain client via the JSON/RPC/HTTP interface
2. JSON is not needed/used in the smart contract

```csharp
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace SupportedStandards1
{
    public class Contract1 : SmartContract
    {
        public static object Main(string operation, params object[] args)
        {
            object result = false;

            if (operation == "supportedStandards")
            {
                result = (object)supportedStandards();
            }

            Runtime.Notify("result", result);

            return result;
        }

        public static string[] supportedStandards()
        {
            string[] result1 = { "NEP-5", "NEP-1234" };

            return result1;
        }
    }
}
```

**Comment by erikzhang** [comment]
@mwherman2000 Returning an array of string is better!

**Comment by erikzhang** [comment]
I am wondering if it is necessary to add a new method: bool checkmethod(string method_name)

It checks whether the specified method exists in the contract.

**Comment by mwherman2000** [comment]
What is your use case Erik? ...an example?

My initial response is that would undermine the objective of this proposal.  If your smart contract says it supports ["NEP-1234"], for example, then it is declaring it faithfully implements all of the *required* operations/methods defined in that specification.  

In principle, going forward, this removes the concept of "optional" operations/methods in NEP specifications.  A replacement for optional operations/methods will be to factor them out as *required methods in a second, separate NEP specification(s)* (e.g. NEP-5678) and then the implementer of a smart contract needs declare whether their SC supports ["NEP-1234"], ["NEP-1234","NEP-5678"] or just ["NEP-5678"] ...but this really means once your SC declares which NEPs it supports, it is required to support the operations/methods declared in those NEPs.

**Comment by erikzhang** [comment]
@mwherman2000 You are right. "Optional" methods should be moved to separate NEP specification(s).

For NEP-5, I'm thinking about whether I should remove those optional functions. Because now the contracts can detect the receiver's `payable` flag to determine whether it can handle the received tokens.

https://github.com/neo-project/neo/pull/233

**Comment by mwherman2000** [comment]
Yes, I think the optional operations/methods can be removed as part of an overall overhaul/update of NEP-5 per my NEP-5 comments:

**Comment by mwherman2000** [comment]
I'll submit a PR for this proposal.
