### ISSUE TITLE
New NEP-Meta/Process: Additional category of proposals called NEO Community Proposals (NCPs)

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/proposals#47]
This is a follow-on to the acceptance of NEP-10 -- prompted by the following question in #dev-general:
```
Kev - Today at 8:00 AM
I see , thanks hal
@Michael Herman (Toronto) For NEP-10, if a user wanted to add a new set of methods to their token,
they would have to wait for it to be approved in the NEP standards? And if it does not get approved?
And If they only wanted or needed some of the required methods of a NEP, they would have to 
implement all of them due to stating that they support NEP-X
What about adding a method that returns an ABI for exposed methods?
```
Here's my reply suggesting we need something like NEO Community Proposals (NCPs)...
```
Michael Herman (Toronto) - Today at 9:25 AM
@Kev Hi... I was actually looking forward to someone asking this category of questions.  
Let me answer them in order.
1. RE: New methods/new NEP/needing to wait for approval/not being approved, etc.  This is the
most interesting question. I think we need a lightweight way for people to quickly submit "NEO
Community Proposals" (or something like that) and quickly receive a "number" ...e.g. ("NCP-1234")
...that they can use with NEP-10.  I see NCPs as potentially being an "on-ramp" to something
becoming an NEP.
2. RE: Needing to implement all of the required methods.  Yes this is a requirement.  The ABI
suggestion doesn't work because it would also need to work for SCs querying and calling other SCs.
ABIs (and JSON) are too complex to be processed internally by a SC 
(discussion: https://github.com/neo-project/proposals/issues/40#issuecomment-384995270).  
If an SC declares it supports "NEP-1234", then it is committing that it supports all of the 
operations/methods in NEP-1234.
Lastly, I want to see the NCP discussion become more formal/tracked.  I've opened this issue to
more formally track this idea: https://github.com/neo-project/proposals/issues/47
CC: @erik @tyler @Hal0x2328
```

**Comment by mwherman2000** [comment]
@erikzhang @lllwvlvwlll

**Comment by erikzhang** [comment]
I think the easiest way is to use the issue/pr number for the NCP number. Because the issue/pr numbers are alloced by github and will never be duplicated.

**Comment by mwherman2000** [comment]
Can we agree the PRs for NCP would be accepted automatically? ...i.e. as soon as an NCP is submitted?

**Comment by erikzhang** [comment]
To make things easier, an issue/pr for a NEP would be accepted automatically as a NCP with the issue/pr number.

**Comment by canesin** [comment]
While I understand the intent this will generate a proliferation of bad implemented/designed standards, let me explain: there is a reason improvements proposals in other chain take time to be accepted or are refused, like developer experience, security, economics, complexity and so on.

Having a meta acceptance would open the option for many contracts to implement "NCP-50" but as a PR NCP-50 could change, so now what does the contract support ? And if it changed because there is a security issue ?

**Comment by mwherman2000** [comment]
Like an NEP, once an NCP has been submitted, it shouldn't/can't be changed ...it needs to stand as an immutable interface contract.  

However, NCPs needs a much shorter/lightwieght review process ...maybe something like: as long as any two (2) or more parties agree on the content and wording of an NCP, it is accepted and numbered.  Something lightweight that can be accomplished in a few hours/days ...not weeks and months ...before the NCP is given a number.

If there are improvements that come along later on, then that would be a new NCP (or NEP) ...with a new number.

**Comment by canesin** [comment]
That makes no sense @mwherman2000, a proposal that can't be changed is not a proposal is a imposition. It will lead to just poorly designed interfaces with problematic deficiencies like I explained before. What you actually trying to achieve is just a way to circumvent the NEP process to push something, two people agreeing into something is not by any means a definition of community acceptance. Imagine, standards done in few hours for blockchain interfaces.

**Comment by mwherman2000** [comment]
...all it takes is for someone to create a new repo :-)

**Comment by mwherman2000** [comment]
Decision (https://github.com/neo-project/proposals/issues/47#issuecomment-392137713): "To make things easier, an issue/pr for a NEP would be accepted automatically as a NCP with the issue/pr number."

Issue closed
