### ISSUE TITLE
NEP numbers should *not* have decimal parts (e.g. "NEP-5.1") - only whole numbers

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/proposals#50]
For example, NEX has some extensions to NEP-5 that they want to call NEP-5.1.
@saltyskip has some NFT extensions that I think he wants to call NEP-5.1.
@mwherman2000 (moi) has some NEP-5 extensions for processing remittances ...maybe I want to be the ".1" in NEP-5.1?

I don't think it makes sense to have decimal parts in NEP numbers. 

Who has the right to be ".1", who is ".2"?  If you're the ".1", do you also have first rights to become ".2" or ".3"?  If you're the ".1" and my spec is the ".2" and some other unrelated spec is ".3", will that make sense to anyone 1, 5, 10 years from now?

The whole situation is avoidable if we stick to whole numbers (i.e. positive integers) e.g. NEP-1234

Do you agree?

p.s. Decimal NEP numbers sort of sound like versioning which is also not a good idea and goes against the spirit of NEP-10.  If you want a new or different interface, create a new NEP (or NCP).

**Comment by mwherman2000** [comment]
CC: @erikzhang @saltyskip @lllwvlvwlll

**Comment by canesin** [comment]
To give my 2cents @mwherman2000 I think that any standard should be a NEP, so with NEP10 I can say that I comply with NEP5 and NEP15 or whatever and that composed is equivalent to the standard the application need, so the application can call a method and determine if it should process further.

**Comment by mwherman2000** [comment]
@canesin I *think* I agree with you Fabio (and I'm glad to see you agree with/support NEP-10). I think the key phase in your comment is "any standard should be a NEP" ...and, more importantly, how do we operationalize this?  

I've made one suggestion here: https://github.com/neo-project/proposals/issues/47 (which @erikzhang  supports ...I'm looking for others to add their comments).

**Comment by canesin** [comment]
@mwherman2000 NEO is a community project already makes no sense for me to have a "NEO Community Proposal" at all, what makes it different then a NEP ? As a matter of fact it is good to have fewer standards.

**Comment by mwherman2000** [comment]
RE: As a matter of fact it is good to have fewer standards.

Not at all. It make sense to have fewer (formal) NEP standards but the spirit of NEP-10 is to create a vibrant ecosystem with gazillions of NCPs/NEPs ...trying to say that the only specifications that are shared across the community are the formal NEP specs only serves to stifle innovation in favor a few large projects.

p.s. ...unless your issue is only with the name (i.e. NEO Community Proposal)... then that's a gentler discussion.

**Comment by canesin** [comment]
Is not only the name, I provided some input in the other issue. We cannot have a "stub" to standard.

**Comment by mwherman2000** [comment]
It's whatever works best for the community ...decided by the community.

**Comment by canesin** [comment]
We can endup with 100s of NEPs for specific things, that is okay - but a standard need to be static, by definition of standard, you can't comply with NEP5 or NEP10 and that means two different things. So for community standards to work, it shoul ... be a NEP ?

**Comment by erikzhang** [comment]
There won't be a decimal part in a NEP number.

**Comment by mwherman2000** [comment]
Decision (https://github.com/neo-project/proposals/issues/50#issuecomment-394061788): "There won't be a decimal part in a NEP number."

Issue closed

**Comment by mwherman2000** [comment]
Decision (https://github.com/neo-project/proposals/issues/50#issuecomment-394061788): "There won't be a decimal part in a NEP number."

Issue closed
