### ISSUE TITLE
Retrospective modification of finalised NEP5

### ISSUE THREAD

**Issue by birmas** [neo-project/proposals#57]
https://github.com/neo-project/proposals/commit/8c6b427e2ada2e71f92081686c4a832351e9eaa0#diff-e5a1452ea0de8fa24b9c328151e94aff

Projects deployed on mainnet have implemented these optional methods. I don't agree that they should have been removed from a proposal that had been marked as final and I put forward that they should be restored.

If a new token standard is to be defined *without* the optional methods then a completely new proposal should be submitted for discussion.

**Comment by mwherman2000** [comment]
In the morning, I'll do what should have been done a week or more ago - I'll fork and PR a new NEP that contains what used to be the optional methods in the old NEP-5 standard.  It will take 15-20 minutes and then we can move on.

**Comment by birmas** [comment]
Ignoring the retrospective editing of a previously finalised nep without any reference to the change..

If this new Nep is proposed as NEP-51 and the original NEP-5 is amended so it is clear that the previously optional methods should be referenced in NEP-51 I think it solves the issues people are having.

**Comment by birmas** [comment]
Closed due to https://github.com/neo-project/proposals/issues/59

**Comment by mwherman2000** [comment]
@erikzhang I've created https://github.com/neo-project/proposals/pull/60 to be reviewed and approved.

@birmas @anfn101 @lllwvlvwlll
