### ISSUE TITLE
Blocked accounts Smart Contract

### ISSUE THREAD

**Issue by vncoelho** [neo-project/proposals#80]
This is a polemic proposal, but that is why we are here.
First of all, there is a strict line between censorship resistance and transparency.

## Motivation

* Currently, blocked account are hardcoded as a configuration of the node clients: https://github.com/neo-project/neo-plugins/blob/db04e756a64c149e86d117fe89879c72f319c7df/SimplePolicy/SimplePolicy/config.json#L7-L10;
* While we do not have any blocked accounts, we can imagine several specific scenarios in the future where an account should be blocked;
* Nowadays, validators are the only ones really able to filter transactions (it will be kept like that in the proposal).

## Solution
* Every voting rule is subjected to a bias, that is why this proposal does not change the way a transaction is filtered compared to the current state;

* In order to achieve better transparency in such aforementioned cases, the idea is to deploy a smart contract with some basic voting functions:
    - Every address can vote for blocking an account, however, only validators votes will still be really counted. This is done for promoting the possibility of public expressed opinions;
    - Receive a signed message with the blocked account;
    - If, at least, `M` validators decide to block an account it will enter in the list. Votes can be reverted at any time;
    - A function for a blocked account to present its public reply.

### Solution positives aspects

* This will not change the current flow, however, promotes transparency;
* Neo Ecosystem will be prepared to face such situations in a decentralized and transparent fashion;
* [Kleros](https://kleros.io/) platform sounds like an interesting case of study for this kind of proposals.

## Expected deadline for implementation

This proposal does not need to be implemented in the next coming months/years, even in Neo 3.0. 
Maybe this is a proposal for something in the future, such as Neo 4.0.

**Comment by igormcoelho** [comment]
Interesting idea! A Smart Contract may be easier (and more transparent) to handle some types of communication, even between consensus nodes.

**Comment by vncoelho** [comment]
Celebration time!
