### ISSUE TITLE
Create NEO 3.0 milestones in this repository

### ISSUE THREAD

**Issue by lock9** [neo-project/proposals#83]
Hello,

Could you guys create the NEO 3.0 milestone in this repository?
I was reading NEO 3.0 issues and noticed that there are a few [links ](https://github.com/neo-project/neo/issues/302)to this repository but there is no milestone. Maybe this can help to choose what NEPs are going to be implemented in version 3.0?

Thanks

**Comment by WyattMufson** [comment]
They have the 3.0 milestone on the main Neo repo here: https://github.com/neo-project/neo/milestone/1
