### ISSUE TITLE
Do we have transferFrom on NEP-5?

### ISSUE THREAD

**Issue by igormcoelho** [neo-project/proposals#95]
Do we have `transferFrom` method on NEP-5? 
Because it's not on spec (yet). Question is: if we have it, we should update spec asap. 
If we want it, but not on NEP-5, will we create another spec for it?

**Comment by igormcoelho** [comment]
This is specially important for NEO3, native tokens.

**Comment by shargon** [comment]
We should have it

**Comment by erikzhang** [comment]
Why do we need it?

**Comment by steven1227** [comment]
The reason for transferFrom is fro DEX(Decentralized Exchange) usage?

**Comment by erikzhang** [comment]
Here are some discussions on `approve` and `transferFrom`:

https://github.com/neo-project/proposals/pull/41#issuecomment-507704430

**Comment by igormcoelho** [comment]
In fact, I don't know if we absolutely need it for NEO3 native tokens... but at least we should know by now what exactly is NEP5 interface :joy: do we have an agreement on that?

**Comment by steven1227** [comment]
> Here are some discussions on `approve` and `transferFrom`:
> 
> [#41 (comment)](https://github.com/neo-project/proposals/pull/41#issuecomment-507704430)

If approve and transferfrom is not needed as the reason is pointed out in this comment, we can close this issue.
