### ISSUE TITLE
About signMessage and verifyMessage

### ISSUE THREAD

**Issue by guangxingmao** [neo-project/proposals#96]
How to signMessage, 
![屏幕快照 2019-07-15 10 49 25](https://user-images.githubusercontent.com/19208420/61193510-4addfc00-a6ee-11e9-9c09-ee4074391c0e.png)
![屏幕快照 2019-07-15 10 49 42](https://user-images.githubusercontent.com/19208420/61193517-529da080-a6ee-11e9-85db-99a887a1a84c.png)
It's so difference!

For exemple:
salt = 058b9e03e7154e4db1e489c99256b7fa;
message = Hello World!
The first:
messageHex = 01000f0 + salt.length + message.toHex + salt + message + 0000 
The second:
messageHex = 01000f0 + (salt+message.toHex).length/2 + salt + message.toHex + 0000

Which kind of signature is right ？
And The source code of verifyMessage
![屏幕快照 2019-07-15 10 56 13](https://user-images.githubusercontent.com/19208420/61193625-32221600-a6ef-11e9-99e1-ee1ec3ecfed6.png)

I tried the exemple 
![屏幕快照 2019-07-15 10 58 24](https://user-images.githubusercontent.com/19208420/61193678-947b1680-a6ef-11e9-9ffa-4e0eb3099b88.png)
![image](https://user-images.githubusercontent.com/19208420/61193752-f176cc80-a6ef-11e9-8cf4-dcc69dbd3a78.png)
the result is false

**Comment by shargon** [comment]
This is not a proposal, so please move this issue to the right project

**Comment by guangxingmao** [comment]
> This is not a proposal, so please move this issue to the right project

ok，tks
